### PR TITLE
Fixes and cleanup for Java tests and CI

### PR DESCRIPTION
**Pull request by raphinesse**
Details in commit messages

### CODE REVIEW

**Comment by dpogue** [comment]
Travis should be running, I'll open an issue with the ASF INFRA team to get it hooked up again. Please let me know if you notice any other repos where it's stopped picking up new PRs.

**Comment by raphinesse** [comment]
@infil00p This is the PR I was talking about earlier. This fixes the Java CI tests for now. I triggered the CI three times so you can have a look at the intermediary results if you like.

I have done some cleanup of the CI configs locally but I still have to work out some details before I file a PR with these changes.

**Comment by shazron** [comment]
@dpogue @infil00p is this good to go?

**Comment by dpogue** [comment]
Looks fine to me, and the tests pass, but @infil00p would know better the gradle requirements and whether this makes sense.

**Comment by raphinesse** [comment]
I added my other CI related changes since they depend on the initial ones. Looking forward to reviews.

This should also fix the failing build for #445

**Comment by raphinesse** [comment]
Just a gentle reminder: Java Unit tests don't run on CI without this.

Would appreciate a review, @infil00p. I can split this up into a few different PRs if preferred.
The following would make sense:
- Fix Java Unit tests (local and on CI)
- Cleanup Java Unit tests
- Cleanup CI configs
- Update supported Node.js versions

**Comment by shazron** [comment]
I don't think Joe can chime in, he can't devote time to this at this juncture -- we'll just have to pull this in since its a blocker for other PRs, and deal with any incompatibilities as they come. I wish I had more input on this matter, but my Android knowledge (especially gradle issues) is minimal. Thoughts?

**Comment by raphinesse** [comment]
Thanks for the info @shazron. I will go ahead, give this a last polish and merge then. I am quite confident that these changes are OK. Furthermore, all of these changes only affect tests. So nothing too dangerous anyway.

**Pull request merged**
