### PR TITLE
Android - Added validation of mime types for fileChooserParams. Fixes #695.

### LINKED ISSUE #695: Missing Intent type and category prevent file upload - [solution included]
# Bug Report
Files upload not working on Android when the Cordova App uses [ng-file-upload](https://github.com/danialfarid/ng-file-upload/issues/2111).

( works on iOS 👇👇  )
image

## Problem
Using [ng-file-upload](https://github.com/danialfarid/ng-file-upload) it is not possible to upload images or document on Android when the App is built using Cordova.

The 2 lines fix suggested below will resolve the Issue opened [here](https://github.com/danialfarid/ng-file-upload/issues/2111) on the ng-file-upload repository and the [related Stackoverflow](https://stackoverflow.com/questions/55261705/file-upload-not-working-for-android-in-cordova-project).

This is the line after which the following 2 lines of code need to be added:
https://github.com/apache/cordova-android/blob/2163c8ae0536bfde9029cfc981b945f4af93e09f/framework/src/org/apache/cordova/engine/SystemWebChromeClient.java#L253

Bug fix - **2 lines of code**:
```
    @TargetApi(Build.VERSION_CODES.LOLLIPOP)
    @Override
    public boolean onShowFileChooser(WebView webView, final ValueCallback<Uri[]> filePathsCallback, final WebChromeClient.FileChooserParams fileChooserParams) {
        Intent intent = fileChooserParams.createIntent();
        // FIX HERE (same as the above handler) vvvvvvvvvvvvvv @@
        intent.addCategory(Intent.CATEGORY_OPENABLE); 
        intent.setType("*/*");
        // FIX HERE ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ @@
```

### What is expected to happen?
The user should be prompted to choose which app to use to pick a file to upload

### What does actually happen?
On click no file picker is shown

## Information
These logs get generated when the upload button that should open the file picker is clicked:

"No activity found to handle file chooser intent.: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.GET_CONTENT cat= [android.intent.category.OPENABLE] typ=.jpg,.png,.tiff,.jpeg,.tif,.pdf }"

### Command or Code
Unfortunately I cannot share the code.

### Environment, Platform, Device
Android app built with Cordova.

Same result using the default WebView and the WebView provided by cordova-plugin-ionic-webview.

### Version information
Same result on cordova-android 7 and 8.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

### PR DESCRIPTION
**Pull request by gabriele-sacchi**
### Platforms affected
Android

### Motivation and Context
This PR solved the issue raised [here](https://github.com/apache/cordova-android/issues/695). 

[ng-file-upload](https://github.com/danialfarid/ng-file-upload/issues/2111) without this change does not work with Cordova. This issue on their repository had been raised a while back and many users had this unsolved issue: https://github.com/danialfarid/ng-file-upload/issues/480

### Description
Added mime types validator/generator in case the mime types passed in through fileChooserParams are not valid. Defaults to "*/*" if not valid mime type is found.

In a nutshell:
```
        Intent intent = fileChooserParams.createIntent();
        List<String> validMimeTypes = extractValidMimeTypes(fileChooserParams.getAcceptTypes());
        if (validMimeTypes.isEmpty()) {
            intent.setType(DEFAULT_MIME_TYPE);
        } else {
            intent.setType(String.join(" ", validMimeTypes));
        }
```

### Testing
Tested on Android simulator and physical device. The file picker is now correctly opened using ng-file-upload.

Utility method tested with various inputs.
Eg. 
- new String[]{null, ".zip", "application/zip", ".pdf", "image/tiff", "text/plain", "boh/bah"} => 
`application/zip application/pdf image/tiff`
- new String[]{".jpg,.png,.tiff,.jpeg,.tif,.pdf"}; => 
`system_process I/ActivityManager: START u0 {act=android.intent.action.GET_CONTENT cat=[android.intent.category.OPENABLE] typ=image/jpeg image/png image/tiff application/pdf cmp=com.android.documentsui/.picker.PickActivity} from uid 10105`
- new String[]{} => used default value

### Checklist

- [X] I've run the tests to see all new and existing tests pass
- [X] I added automated test coverage as appropriate for this change
- [V] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [V] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [X] I've updated the documentation if necessary

### CODE REVIEW

**Comment by nshoes** [comment]
Any word on merging this?

**Comment by timbru31** [comment]
@nshoes - Nobody has reviewed this PR yet, so ETA if and when this might be merged.

**Comment by nshoes** [comment]
😢

**Comment by WuglyakBolgoink** [comment]
up

**Comment by WuglyakBolgoink** [comment]
we need this urgent... ;-(

**Comment by WuglyakBolgoink** [comment]
up

**Comment by erisu** [comment]
Thank you for your contribution with this PR, but this issue should have already been resolved with PR #971 which had been merged in.

Closing out this PR.

**Pull request closed without merging**
