### PR TITLE
CB-10837 Support platform-specific orientation on Android

### PR DESCRIPTION
**Pull request by vladimir-kotikov**
This removes processing of "orientation" preference lets user to specify any platform-specific value for Android.

See [CB-10837](https://issues.apache.org/jira/browse/CB-10837)

### CODE REVIEW

**Comment by vladimir-kotikov** [comment]
Note that to fix orienattion issues ultimately we'll need also https://github.com/apache/cordova-lib/pull/411 and https://github.com/apache/cordova-lib/pull/412

**Comment by omefire** [comment]
What happens if the orientation provided is not supported by the Android platform ?

**Comment by vladimir-kotikov** [comment]
When set invalid value gradle failed with

```
:processDebugResources
E:\PROJECTS\Temp\foo\platforms\android\build\intermediates\manifests\full\debug\AndroidManifest.xml:35:40-43 : AAPT: String types not allowed (at 'screenOrientation' with value 'foo').
```

**Comment by omefire** [comment]
Ok, its better we leave the validation to gradle then.

**Comment by omefire** [comment]
LGTM!

**Pull request closed without merging**
