### PR TITLE
CB-9519 Fix the engine destruction bug

### PR DESCRIPTION
**Pull request by NoLongerLazyDhl**

### CODE REVIEW

**Comment by DILEEP-YADAV** [comment]
http://www.plugbunch.com/

**Comment by nikhilkh** [comment]
@vladimir-kotikov Can you please review - as we look to do a new release - does this change need to be included?

**Comment by vladimir-kotikov** [comment]
@nikhilkh, i'm not 100% sure - according to comments in the code it might sense to have this checked in, but looking at where this code was introduced [`087ec11`#L625](https://github.com/apache/cordova-android/commit/087ec11e6abc61acde4e2860f8ee363f3daba578#diff-08c0ff867a9ff2aaaa99017464f55684L625), it was always working this way - we never wait for `about:blank` being loaded.

@NoLongerLazyDhl, could you please add some details about the problem, which this change solves? Maybe repro steps?

**Comment by NoLongerLazyDhl** [comment]
@vladimir-kotikov When I want to receive the "exit" message in my activity which extends CordovaActivity to do something, it make that I'm not able to receive the message. That's it solves.

**Comment by DILEEP-YADAV** [comment]
ok

**Comment by infil00p** [comment]
Can this be added to master and not to 4.0.x?

**Comment by infil00p** [comment]
Can you please close this pull request and reformat it to be against master? Thanks!

**Pull request closed without merging**
