### PR TITLE
[WIP] Cleanup build.gradle defaults not used

### PR DESCRIPTION
**Pull request by brodybits**
- remove `defaultTargetSdkVersion` which was never used
- comment out `defaultBuildToolsVersion` & `defaultCompileSdkVersion` for now

This is a quick-fix solution for #658.

### CODE REVIEW

**Comment by oliversalzburg** [comment]
LGTM

**Comment by brodybits** [comment]
> `FUTURE TBD` is not something that should be in the code but an issue on GitHub.

Reworded, with blank lines inserted as well. I *did* already raise issues concerning the defaults which should be used someday in the future.

> Are we sure those are not needed anywhere? Why were they here before? Did you investigate why/when they were added?

I would say yes. I *did* grep through the Gradle files to hopefully ensure that I got it right. Details about where and how the defaults were introduced are in issue #658.

**Comment by janpio** [comment]
(I didn't actually want to approve this, as I have no idea what it could break. But I can't find a way to remove the approval without requesting changes - which I also don't want to do. Please someone else approve this before merging.)

**Comment by brodybits** [comment]
I am closing this one for now.

As I said in <https://github.com/apache/cordova-android/pull/655#issuecomment-462584932> we may still need to deal with target SDK version.

Issue #658 (default SDK values never used) remains unsolved at this point.

**Pull request closed without merging**
