### PR TITLE
feat: bump appcompat@1.3.0

### PR DESCRIPTION
**Pull request by erisu**
### Motivation, Context & Description

Bump AndroidX AppCompat to `1.3.0`. Using the new centralized configuration defaults.

### Testing

- `npm t`

### Checklist

- [x] I've run the tests to see all new and existing tests pass

### CODE REVIEW

**Comment by jcesarmobile** [comment]
Where do you check latest versions available?
I can't see it here 
https://mvnrepository.com/artifact/androidx.appcompat/appcompat?repo=google

**Comment by erisu** [comment]
@jcesarmobile lets hold off on this one.

From the link you provided and Google Android docs, only `1.4.0-alpha03` exists.

Some reason when in Android Studio, it was suggesting me to upgrade to `1.4.0`, but it didnt say anything about `alpha`.

**Comment by erisu** [comment]
@jcesarmobile 

https://maven.google.com/web/index.html?q=androidx.app#androidx.appcompat:appcompat:1.3.0

**Comment by erisu** [comment]
Actually from your link, it seems to also be listed under the `scijava-public` tab.

I am not sure what to do with this PR.

**Review by jcesarmobile — APPROVED** [review]
scijava-public packages are in a different location (http://maven.scijava.org/content/repositories/public/) than regular google packages (https://maven.google.com/), but yeah, it's published correctly on the later, so I guess that's ok and might just be some error on the mvnrepository site.

I've set the version to 1.3.0 and it gets downloaded without problems, so I guess it's ok

**Pull request merged**
