### PR TITLE
CB-11153 Use Gradle 2.8 correctly for building Android projects

### PR DESCRIPTION
**Pull request by nikhilkh**
This improves gradle build performance by 1 second on my machine

@jasongin; @infil00p; @riknoll  to help review

### CODE REVIEW

**Comment by infil00p** [comment]
Why 2.8? Why not 2.10?   Is 2.10 slower than 2.8?  Will this break other users somehow?

**Comment by nikhilkh** [comment]
I just ended up moving to version 2.13 which is the latest - and the perf is even a bit better than version 2.8. I looked at Android docs and did not find anything about one version being more compatible than other - so we should be fine.

**Comment by infil00p** [comment]
Good call on updating this to Gradle 2.13, I just updated to 2.1.0 beta, and Android Studio just showed me a bunch of complaints about importing the project.

**Comment by infil00p** [comment]
OK, I merged this in, because I need it for something I'm working on :P

**Pull request closed without merging**
