### PR TITLE
refactor!: drop support for `android` SDK tool

### PR DESCRIPTION
**Pull request by raphinesse**
### Motivation and Context

We have multiple places where we support both the legacy `android` SDK tool as well as [`avdmanager`](https://developer.android.com/studio/command-line/avdmanager) and [`sdkmanager`](https://developer.android.com/studio/command-line/sdkmanager) from current SDK tools. This makes code more complicated and maintenance more difficult.

This PR removes the support for the `android` CLI tool from our code base. After this change, to use `cordova-android` users will need either:
- Revision 25.3.0 (March 2017) or greater of the [Android SDK Tools](https://developer.android.com/studio/releases/sdk-tools)
- any version of the [new command-line tools](https://developer.android.com/studio#cmdline-tools) which are also included in Android Studio

Closes #595 #741

### Description

- `emulator.list_images` now always uses the `avdmanager` binary.
- `android_sdk.list_targets` now always uses the `avdmanager` binary.
- `check_reqs.check_android` does not consider legacy `android` binary for SDK detection anymore
- We do not give error messages that involve using the legacy `android` binary anymore

There are multiple opportunities for further simplification after the code removal in this PR. I already have seized some of these in a local branch but I would prefer to open new PRs for these after this is merged.

### Testing

- Existing unit and E2E tests pass
- The following manual tests give the expected results on my machine:
  - `node -e "require('./bin/templates/cordova/lib/emulator').list_images().then(console.log)"`
  - `node -e "require('./bin/templates/cordova/lib/android_sdk').list_targets().then(console.log)"`
  - `node -e "require('./bin/templates/cordova/lib/check_reqs').check_android().then(console.log)"`

### CODE REVIEW

**Review by purplecabbage — APPROVED** [review]
Looks good to me!

**Review by breautek — APPROVED** [review]
lgtm

Tested adding the platform and building/running on emulator using one of my apps.

**Review by erisu — APPROVED** [review]

**Comment by raphinesse** [comment]
Thanks for the review everyone! Since this is a breaking change for next major, how do we want to continue with this PR?

- merge it into master now
- leave it sitting open until we're confident not to release patches/minors for 9 anymore
- integrate it into a long-running `next-major` branch where we collect breaking changes for next major

Side note: I will probably need some integration branch for multiple breaking changes anyway

**Comment by breautek** [comment]
> integrate it into a long-running next-major branch where we collect breaking changes for next major

This might be a good idea for testing PRs against the collection of other breaking changes to be released.

**Pull request merged**
