### PR TITLE
fixed bad target+mini sdk version

### PR DESCRIPTION
**Pull request by neo5anderson**
### Platforms affected
android

### Description

change targetSdkVersion and minSdkVersion gen template.

### Testing

test case has one failed, but I don't know why the sort fail, and I have nothing to do with that.
use `bin/create` tested, project sync fine

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Comment by janpio** [comment]
What issue does this PR refer to?

**Comment by neo5anderson** [comment]
> What issue does this PR refer to?

I think it will help for #675, and it works for my projects

**Comment by brodybits** [comment]
Thanks @neo5anderson for the contribution. I think PR #699 solves the issue in a more general purpose way.

**Comment by erisu** [comment]
Closing out this PR as it should no longer be required with the changes of #699.

**Pull request closed without merging**
