### PR TITLE
CB-12465: Rewrite of the Unit Tests

### PR DESCRIPTION
**Pull request by infil00p**
### Platforms affected
Android

### What does this PR do?
Re-writes the Unit Tests so that we have some unit tests.

### What testing has been done on this change?
I made sure there were tests.

### Checklist
- [x ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [x] Added automated test coverage as appropriate for this change.  (HOLY CRAP, I CAN ACTUALLY CHECK THIS BOX OFF NOW FINALLY!  YAY!!!)

### CODE REVIEW

**Comment by fujunwei** [comment]
It hangs on running unit tests with `./gradlew connectedAndroidTest`, the output logs:
> org.apache.cordova.unittests E/AndroidProtocolHandler: Unable to open asset URL: file:///android_asset/www/htmlnotfound/index.html

**Comment by infil00p** [comment]
@fujunwei I don't think the test should hang, but that's technically a failure of the test and not a problem with the test itself.

**Comment by fujunwei** [comment]
Do you mean the failed test will be continue to fix?

**Comment by infil00p** [comment]
@fujunwei Well, when you debug the test, it's clear that it's not redirecting to the error page that the intent defines, and instead it's going to some other page or showing a dialog window.  This isn't a huge failure (in fact, this is probably a minor or trivial priority bug, since it's still a html not found error page, which should never happen on a Cordova app), but it should actually fail.

**Comment by infil00p** [comment]
@fujunwei OK, yeah, this is a minor mistake.  The errorUrl wasn't correct in the config.xml, the test passes and it no longer hangs.

**Comment by infil00p** [comment]
FYI: I'll be collapsing the commits on Friday when I merge this thing in.

**Comment by fujunwei** [comment]
There is a test failed on SM-G9250.
> org.apache.cordova.unittests.IFrameTest > iFrameHistory[SM-G9250 - 6.0.1] FAILED 
at junit.framework.Assert.fail(Assert.java:48)

And there are two tests failed on Android Things platform.
>  org.apache.cordova.unittests.BackButtonMultipageTest > testViaBackButtonOnView[iot_joule - 7.0] FAILED  at android.support.test.espresso.NoActivityResumedException: No activities in stage RESUMED. Did you forget to launch the activity. (test.getActivity() or similar)?

> org.apache.cordova.unittests.IFrameTest > iFrameHistory[iot_joule - 7.0] FAILED at android.support.test.espresso.NoActivityResumedException: No activities in stage RESUMED. Did you forget to launch the activity. (test.getActivity() or similar)?

**Comment by infil00p** [comment]
@fujunwei There's a threading/concurrency issue with Espresso and checking the WebView's URI.  I'm trying to adopt Espresso to reduce the amount of code in the test, but there's no docs on how to check the URI of a WebView, which I find utterly bizzare.  It'd be good to get rid of all the runOnUriThread wrappers on that method somhow.  That being said, throwing a sleep does brute force the test to work for now.

I don't have any devices running Android Things yet.  I'm going to see about fixing that today.

**Comment by fujunwei** [comment]
All the tests has passed after updating the latest codes, thanks.

**Comment by fujunwei** [comment]
LGTM

**Pull request closed without merging**
