### PR TITLE
CB-5968 (Android) - Missing the drawable-xxhdpi folder

### PR DESCRIPTION
**Pull request by sterlingann**
### Platforms affected

Android
### What does this PR do?

modified template so that xxhdpi and xxxhdpi directories are now automatically generated for drawables and mipmaps.   Aspect ratios are changed slightly because I did a simple scale from hdpi.  
### What testing has been done on this change?

created a test project to make sure that the new folders and images were autogenerated 
### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [x] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by dpogue** [comment]
I believe the xxhdpi icon should be 144×144, rather than 192×192.

The xxhdpi splash screen is 960×1600. The xxxhdpi one is 1280×1920.

**Comment by sterlingann** [comment]
Thanks @dpogue !  I updated the xxhdpi icon to 144 x 144.  It looks to me like the splash screens are already 960x1600(xxhdpi) and 1280x1920(xxxhdpi).

**Comment by purplecabbage** [comment]
Please update the title of this pr, per checklist item 2
**CB-5968 (android) Missing the drawable-xxhdpi folder**

**Comment by rodriguesgm** [comment]
I don't know if this is related with the issue I'm having, so maybe someone can help me. I'm using phonegap-plugin-push with Ionic2 and my custom icon for notifications are not working, they are not showing on android bar. It was working some months ago, but when I updated the Ionic2 to RCx, it stop working. Thiis is a related issue with the problem https://github.com/driftyco/ionic/issues/9270.

Does anyone have some clue to help me?

**Comment by dpogue** [comment]
That is unrelated, and probably an issue with the phonegap-plugin-push.
Cordova-Android doesn't do anything related to notifications, or notification-specific icons.

**Comment by rodriguesgm** [comment]
thanks @dpogue

**Pull request merged**
