### PR TITLE
CB-9255: make getUriType case insensitive

### PR DESCRIPTION
**Pull request by cjpearson**

### CODE REVIEW

**Comment by omefire** [comment]
the code looks good. However, I'm curious : is there any specific use case this breaks ? or is it more like cleanup ?

**Comment by cjpearson** [comment]
The file transfer plugin uses this method to ensure that a url uses http or https. We would get INVALID_URL_ERR whenever a user entered a url with a capital h in Http. We've worked around this by lowercasing the scheme automatically, but this seems like something that could cause issues again.

**Comment by purplecabbage** [comment]
Makes sense to me.

**Comment by omefire** [comment]
@cjpearson, it does make sense. thanks for the explanation.

**Comment by vladimir-kotikov** [comment]
LGTM. The build seems to fail due to some Travis internal issues with Android SDK.

**Pull request closed without merging**
