### PR TITLE
Always put the Google repo above jcenter

### LINKED ISSUE #521: cordova build android : Could not find intellij-core.jar
```
cordova -v
8.1.2 (cordova-lib@8.1.1)

 cordova platform list
Installed platforms:
  android 7.1.1


cordova build android

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':CordovaLib'.
> Could not resolve all files for configuration ':CordovaLib:classpath'.
   > Could not find intellij-core.jar (com.android.tools.external.com-intellij:intellij-core:26.0.1).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/external/com-intellij/intellij-core/26.0.1/intellij-core-26.0.1.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
```

thank you

see also another recent report of same issue : https://forum.ionicframework.com/t/ionic-pro-package-failed-after-successful-deploy/145355

### PR DESCRIPTION
**Pull request by dpogue**
### Platforms affected
Android

### What does this PR do?
Resolves #521 

### Checklist
- [ ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by millerf** [comment]
> Can we get a minor release with this? We have a broken build that requires modifying this manually.

Same thing here!

**Comment by jeffersoncardoso** [comment]
> We'll make a patch release 7.1.2 whenever someone has time to start the process and submit it to the list for voting.

Same

**Comment by Jule-** [comment]
> We'll make a patch release 7.1.2 whenever someone has time to start the process and submit it to the list for voting.

@dpogue any news?

**Comment by dpogue** [comment]
Cordova-Android 7.1.2 is published, blog post should be up shortly

**Comment by Jule-** [comment]
@dpogue Awesome! Thanks!

**Pull request merged**
