### PR TITLE
CB-9616 AndroidM Runtime Permission Support

### PR DESCRIPTION
**Pull request by ogoguel**
Add onRequestPermissionsResult handler for plugins

### CODE REVIEW

**Comment by DILEEP-YADAV** [comment]
http://www.plugbunch.com/

**Comment by infil00p** [comment]
We're already working on a more robust way of handling the permission requests.

**Comment by ogoguel** [comment]
Good to know :)
I had to implement this feature to test my plugin, and I've though it could be helpful to other people until the official release is out.
Keep up the good work!

**Comment by infil00p** [comment]
Check out #223 for the new API updates, it's a lot of the same code, but abstracts the permission checking code out of the individual plugins.

**Pull request closed without merging**
