### PR TITLE
[WIP] Add Node.js 12 to CI WIP with known test failure

### PR DESCRIPTION
**Pull request by brodybits**
This includes a change that @janpio pushed to the `janpio-travis_node_12` branch (draft PR #766).

~~I discovered that there is a hidden failure on Node.js 12, as reported by @breautek in #768. While output shows a single `F` character, the build seems ignore this failure on both Travis CI and AppVeyor CI.~~

~~I think that further discussion of the ignored test failure should continue in #768.~~

~~P.S. For some reason Travis CI still does not work on Node.js 12, which is very strange since this does work on my fork. But we can still see the ignored test failure on Node.js 12 on AppVeyor CI.~~

_Now with known test failure on Node.js 12, as reported in #767. The trick is to add `dist: trusty` setting near the beginning of `.travis.yml`._

### CODE REVIEW

**Comment by brodybits** [comment]
I find it really strange that Travis CI succeeds (with the ignored test failure) on Node.js on my fork but while it errors on the main Apache cordova-android project. Any ideas?

**Comment by janpio** [comment]
That is indeed strange, although I don't really understand why this needs another PR besides #766.

**Comment by brodybits** [comment]
I just merged the recent test updates, which now give us build failures on Node.js 12 as expected (see #767).

But Node.js 12 on Travis CI seems to error on the Apache build (<https://travis-ci.org/apache/cordova-android/jobs/558578993>) while it fails on my fork (<https://travis-ci.org/brodybits/cordova-android/jobs/558578976>).

I wonder if we should send this to INFRA?

@janpio?

**Comment by janpio** [comment]
Under "Build system information" you see:

Apache build:
```
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
```

Your build:
```
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

**Comment by janpio** [comment]
(misclick)

**Comment by brodybits** [comment]
Explicit `dist: trusty` setting in `.travis.yml` seems to solve the build error, now down to the test error reported in #767.

**Comment by janpio** [comment]
AppVeyor seems to be a different error:

```
npm install
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN tarball tarball data for eslint@^4.19.1 (sha512-bT3/1x1EbZB7phzYu7vCr1v3ONuzDtX8WjuM9c0iYxe+cq+pwcKEoQjl7zd3RpC6YOLgnSy3cTN58M2jcoPDIQ==) seems to be corrupted. Trying one more time.
npm WARN tar ENOENT: no such file or directory, open 'C:\projects\cordova-android\node_modules\.staging\source-map-80867f65\dist\source-map.debug.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\projects\cordova-android\node_modules\.staging\jsesc-454d136c\man\jsesc.1'
npm WARN tar ENOENT: no such file or directory, open 'C:\projects\cordova-android\node_modules\.staging\json-stable-stringify-without-jsonify-8beccf72\test\cmp.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\projects\cordova-android\node_modules\.staging\json-stable-stringify-without-jsonify-8beccf72\test\nested.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\projects\cordova-android\node_modules\.staging\json-stable-stringify-without-jsonify-8beccf72\test\replacer.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\projects\cordova-android\node_modules\.staging\json-stable-stringify-without-jsonify-8beccf72\test\space.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\projects\cordova-android\node_modules\.staging\json-stable-stringify-without-jsonify-8beccf72\test\str.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\projects\cordova-android\node_modules\.staging\json-stable-stringify-without-jsonify-8beccf72\test\to-json.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\projects\cordova-android\node_modules\.staging\doctrine-d55c8be6\lib\doctrine.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\projects\cordova-android\node_modules\.staging\resolve-a9bc0a20\test\node_path\x\ccc\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\projects\cordova-android\node_modules\.staging\resolve-a9bc0a20\test\resolver\same_names\foo.js'
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm ERR! path C:\projects\cordova-android\node_modules\.staging\eslint-32acc61e\CHANGELOG.md
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\projects\cordova-android\node_modules\.staging\eslint-32acc61e\CHANGELOG.md'
npm ERR!  [OperationalError: EPERM: operation not permitted, unlink 'C:\projects\cordova-android\node_modules\.staging\eslint-32acc61e\CHANGELOG.md'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, unlink 'C:\projects\cordova-android\node_modules\.staging\eslint-32acc61e\CHANGELOG.md'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'unlink',
npm ERR!     path: 'C:\\projects\\cordova-android\\node_modules\\.staging\\eslint-32acc61e\\CHANGELOG.md'
npm ERR!   },
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink ' +
npm ERR!     "'C:\\projects\\cordova-android\\node_modules\\.staging\\eslint-32acc61e\\CHANGELOG.md'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\projects\\cordova-android\\node_modules\\.staging\\eslint-32acc61e\\CHANGELOG.md',
npm ERR!   parent: 'rewire'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
```

**Comment by brodybits** [comment]
> AppVeyor seems to be a different error:
> […]

Yes, that error came up at the end. Looks like something flakey :-(

**Pull request closed without merging**
