### PR TITLE
CB-11343: Handle Java versions after JEP-223

### PR DESCRIPTION
**Pull request by ankon**

### CODE REVIEW

**Comment by infil00p** [comment]
So, how do we test this one? Is this a Mac OS X or Linux issue?

**Comment by ankon** [comment]
> So, how do we test this one? Is this a Mac OS X or Linux issue?

It's a "whereever you are able to run Java 9 (EA)"-issue.

**Comment by infil00p** [comment]
Yeah, I'm amazed this fails, since I've been working on a different issue with this regex for a day finding out that check_reqs.js needs to be redone entirely because it just wants a result, literally any result.

**Comment by ankon** [comment]
I'm not sure I follow here. In any case, what is needed to get this forward, and prepare the plugin for actually working with JDK 9?

**Comment by infil00p** [comment]
I couldn't even get Java 9 to work with Android when I installed it, even when it did pass the check, so for now I don't think I can accept this request right now.  If you can try to update the Regex with the new branch, and show that you can actually compile Hello World using Java 9 Early Access, I might reconsider.

**Pull request closed without merging**
