### PR TITLE
CB-8717 Write cordova-android@4.0.0 release notes

### PR DESCRIPTION
**Pull request by jpchase**

### CODE REVIEW

**Comment by clelland** [comment]
It seems so small now.. only 17 changes :)

**Comment by jsoref** [comment]
@jpchase: https://github.com/apache/cordova-android/compare/master...jsoref:pr/167?expand=1

Please consider folding in these changes (I can't seem to make a pull request against your repo)

**Comment by jpchase** [comment]
@jsoref I included some of the corrections from your changes.  I believe the release notes read better with less formatting, so I excluded many of your changes.  Finally, I didn't link to the Whitelist Guide as I wasn't sure which would be the correct link, and I didn't want to link to the edge docs (as that wouldn't make sense over time).

**Comment by jsoref** [comment]
It might be good to get an answer for the Whitelist Guide -- that seems useful to have.

Also, I'd personally encourage you to fold your changes together, there's no real need for people to see the intermediate changes.

**Pull request closed without merging**
