### PR TITLE
CB-13580: (android) fix build for multiple apks (different product flavors)

### PR DESCRIPTION
**Pull request by DavidStrausz**
### Platforms affected
cordova-android

### What does this PR do?
This PR fixes the build if cdvBuildMultipleApks is set to true by defining `flavorDimensions "default"` in `build.gradle` and by adapting the `findOutputApksHelper` method in `GenericBuilder.js` to recursively scan the `build/outputs/apk` directory for matching candidates.

A positive side-effect of this is that builds with crosswalk will work again :-)

### What testing has been done on this change?
I ran the unit tests and the connectedAndroidTest tests and did manual tests of builds with crosswalk (multiple APKs) and builds without crosswalk (single APK).

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by infil00p** [comment]
@DavidStrausz Fix the lint errors and I'll merge this in.  I tried adding more flavours and it kept crapping the bed on me.  I didn't realize that just adding default would get this to work properly again. 

If you're inclined, you can always send a PR to my Crosswalk repo.  It's technically the "official" repo, and if you could get that working, that would win you some serious cred.  (And yeah, I'll merge it in, because I can do that, even though I'm not technically supposed to).

**Comment by DavidStrausz** [comment]
@infil00p Done! 👍  Yeah it also took me some time to figure it out. But the migration guide was really useful if read carfully. 

I will definitely keep that in mind for future contributions, thanks for pointing that out!

**Comment by fredgalvao** [comment]
@DavidStrausz thank you for this.

@infil00p Considering that the combination of the following aspects:
- Oreo
- crosswalk breakage
- wave of plugin updates

is quite important and that crosswalk usage is considerably high (my estimate, no data), what are the chances of a 6.4.1/6.5.0 coming out soon to include this? I'm interested in your PoV in this subject.
I've seen many people delaying/cancelling upgrade plans because of that on the cordova slack channels, and I'd say it would bring a lot of people/projects up to speed again (including mine).

**Comment by infil00p** [comment]
@fredgalvao The next version of Cordova-Android will be 7.0.0, and this will be a breaking change where we finally update the project structure to work with Android Studio, as opposed to the cobbled legacy project layout that we're using today.  I don't have any plans on releasing a 6.4.1 release at this time.

**Comment by fredgalvao** [comment]
@infil00p Unfortunately, for some projects, migrating out of crosswalk isn't really a [`crosswalk in the park`](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/issues/154). I share your mindset nevertheless, I'm just looking for a way to be able to upgrade stuff without having to wait for a long-term upgrade plan to migrate data for users.

Thanks for the info, and I'm looking forward to 7.0.0.

**Comment by fredgalvao** [comment]
I'll just let it documented here to anyone looking for a way out, that @dpa99c has taken the initiative to make a plugin that can migrate data from Crosswalk to the system webview, to be used to move out of Crosswalk.

https://github.com/dpa99c/cordova-plugin-crosswalk-data-migration

**Comment by Robula** [comment]
Did this affect the output path to APKs? 

I'm seeing that the the output is now:
`build/outputs/apk/release/android-release.apk`
Where previously it was:
 `build/outputs/apk/android-release.apk`

I've created an issue in the relevant place where I am experiencing problems.
https://github.com/Microsoft/vsts-cordova-tasks/issues/81

**Comment by DavidStrausz** [comment]
@Robula The output path was not affected, it changed with the gradle upgrade. This PR just fixed how an already output *.apk is found in the `build/outputs/apk` directory.

**Comment by Robula** [comment]
@DavidStrausz Thank you for the explanation. That is strange as I am seeing a difference in output paths between 6.3.0 and 6.4.0. I'll trash my platforms and plugins and reconfirm.

**Comment by ataraxus** [comment]
Hello folks, 

foremost, thanks @DavidStrausz for your effort and explanation! 

But seriously, i know this is symptomatic for the JS world, but introducing breaking changes with a minor release? WTF!? The Ionites do have the cordova dependency declared as **^6.2.3**  so after checking out the project from scratch and building it we get a broken build! Due to the Crosswalk issue and due to changed output directories.

Now, i guess to rub salt and tequila in my eyes, instead of somehow fleshing out a bugfix release, I'm supposed to ditch Crosswalk and my android < 5 user base!? Seriously? 

I know that my post is not helpful in anyway and also symptomatic for the JS world, but so be it - I'm defeated.

Cheers to all who try to make stuff working!

**Comment by Ankoul** [comment]
This issue has been merged, but this code are not on release 7.0.0 and i still getting flavors error. 
If add 'flavorDimensions "default"' on gradle.build manually it works perfectly, but cordova-android will override it on any "platform add android". Does someone knows a stable version with have this code?

**Pull request merged**
