### PR TITLE
CB-10894 Add supports-screens config from the config.xml file

### PR DESCRIPTION
**Pull request by akofman**
Just added the availability to update the supports-screens element of the `AndroidManifest.xml` file from the `config.xml` file.

### CODE REVIEW

**Comment by infil00p** [comment]
This LGTM, but I'm going to need an ICLA assuming you don't already have one.
http://www.apache.org/licenses/#clas

**Comment by akofman** [comment]
I already have one, do you want me to send it to you by e-mail ?

**Comment by shazron** [comment]
CLA verified for Alexis Kofman: http://people.apache.org/unlistedclas.html

**Comment by infil00p** [comment]
I'm going to close this PR with an empty commit.  The config-changes code added recently makes this change no longer needed, since you can just do this:

`<edit-config file="AndroidManifest.xml" target="/manifest" mode="merge">
<supports-screens android:resizeable=["true"| "false"]
                  android:smallScreens=["true" | "false"]
                  android:normalScreens=["true" | "false"]
                  android:largeScreens=["true" | "false"]
                  android:xlargeScreens=["true" | "false"]
                  android:anyDensity=["true" | "false"]
                  android:requiresSmallestWidthDp="integer"
                  android:compatibleWidthLimitDp="integer"
                  android:largestWidthLimitDp="integer"/>
</edit-config>`

**Pull request closed without merging**
