### PR TITLE
Ignore more Gradle build artifacts in Android project

### PR DESCRIPTION
**Pull request by brodybits**
I hope we can get this in before the next major release for Cordova 9 (apache/cordova#10).

P..S. These artifacts are generated by Gradle when the user does `cordova build android` or `cordova run android`.

### CODE REVIEW

**Comment by janpio** [comment]
Why?
Why wasn't this in there before? Why should this be in now?

**Comment by brodybits** [comment]
I just added the info to the description and resolved the conflict. I hope it is clear now, would be happy to answer any other questions.

**Comment by brodybits** [comment]
Thanks @janpio! I didn't see that link before, just added a couple more artifacts.

**Comment by janpio** [comment]
Umm, do we actually have those? Otherwise those are not really necessary to include. But well, it's merged already.

**Pull request merged**
