### PR TITLE
CB-10096: Upgrading to Gradle Plugin 2.1.0

### PR DESCRIPTION
**Pull request by infil00p**
This is a minor change, but I need people running stable to make sure it works. @riknoll Can you take a quick look?

### CODE REVIEW

**Comment by riknoll** [comment]
Sure, I'll try it out

**Comment by riknoll** [comment]
I built/ran mobilespec with and without crosswalk and I didn't encounter any issues. One weird thing that did happen was that I wasn't able to increase the size of the gradle daemon heap from within gradle.properties. Gradle's build output was advising me to edit my gradle.properties file so that I could use the new dexing-in-process feature, but I couldn't get that to work.  Passing it as an argument worked:
```
cordova build android -- --gradleArg=-Dorg.gradle.jvmargs=-Xmx2048M
```

**Comment by infil00p** [comment]
@riknoll Did you test Instant Run on Android Studio? I don't expect this to work with Crosswalk.  We need help from them getting Crosswalk to work with the new Gradle stuff

**Comment by riknoll** [comment]
I tried it out a bit just now (without crosswalk). Java code changes refreshed fine for me. The webview gets restarted of course, but my java changes were reflected as expected and the app did not get restarted. Changes to js, html, etc. were less speedy (app gets killed/restarted). I was just building mobilespec so I didn't really see any drastic improvements in that scenario since it already builds pretty quickly. Are there any specific scenarios you want me to try out?

**Comment by infil00p** [comment]
@riknoll It should skip HTML and JS changes.  If not, this isn't really worth doing other than correctness.

**Comment by nikhilkh** [comment]
@infil00p  Let's get this in - I get a prompt in Android Studio without this.

**Comment by infil00p** [comment]
OK, I pushed this in.  Closing

**Pull request closed without merging**
