### PR TITLE
feat: add custom repositories support

### PR DESCRIPTION
**Pull request by breautek**
This is to correct a big rebase booboo.

Original PR and credit goes to https://github.com/apache/cordova-android/pull/867

### CODE REVIEW

**Review by erisu — APPROVED** [review]

**Comment by mattdsteele** [comment]
@breautek This looks amazing, I am so excited to use this! Is there any documentation or examples of how a to apply a custom registry? It's unclear to me what I should modify, sorry.

**Comment by dirien** [comment]
Hi @mattdsteele , just add "your" repos to the repositories.gradle. It will pick them up from there.

**Comment by erisu** [comment]
@mattdsteele please also read the description of the original PR, which the link can be found in this PR's description. It will contain the `config.xml` the setup.

**Comment by goffioul** [comment]
> As it has been pushed as a minor release, it would probably have been wiser to make the `apply from:` statement in `allprojects` conditional to the existence of `repositories.gradle`.

E.g. a slightly more robust logic for `allprojects` could maybe be:
1. load `repositories.gradle` from current project directory
2. if file in 1. does not exist, load `repositories.gradle` from root project directory

The template project would then only need to provide a single `repositories.gradle` at the top-level and avoid having to copy the same file at multiple locations.

**Pull request merged**
