### PR TITLE
CB-10710 Respect plugman's www option when installing plugins

### PR DESCRIPTION
**Pull request by vladimir-kotikov**
JIRA [CB-10710](https://issues.apache.org/jira/browse/CB-10710)

This change returns back an ability to specify alternative destination for `www` files when installing plugin using Plugman CLI.

### CODE REVIEW

**Comment by dblotsky** [comment]
Is this supported in other platforms too?

**Comment by dblotsky** [comment]
Are there tests for this? I don't know how to test this to verify that the fix works.

**Comment by vladimir-kotikov** [comment]
> Is this supported in other platforms too? If not, should it be?

It sound like platform-agnostic Plugman's feature, so my thinking is that it should. The PRs for other platforms is on their way.

> Are there tests for this? I don't know how to test this to verify that the fix works

Here is verification steps: 

    cordova create foo && cd foo
    cordova platform add android@https://github.com/msopentech/cordova-android#CB-10710
    plugman -d install --platform android --project platforms/android --plugin cordova-plugin-statusbar --www my/custom/www/dir

Then verify the contents of `/my/custom/www/dir`. Plugin js files should be there along `with cordova_plugins.js` Also there should be no `cordova-plugin-statusbar` files neither in platforms/android/platform_www nor in platforms/android/assets/www

**Comment by dblotsky** [comment]
Okay, those steps passed for me on OS X.

**Pull request closed without merging**
