### PR TITLE
feat!: bump Gradle 7.6 & AGP 7.4.2

### PR DESCRIPTION
**Pull request by erisu**
### Motivation and Context

Use latest available Gradle & Android Gradle Plugin

### Description

Updated the following versions:

Gradle: 7.6
Android Gradle Plugin: [7.4.2 (Current)](https://developer.android.com/reference/tools/gradle-api)

### Testing

n/a

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Review by breautek — APPROVED** [review]

**Comment by jcesarmobile** [comment]
Should we go with gradle 8? It’s already available and recommended by android studio Flamingo, which is still in beta but will be released in the coming months

**Comment by erisu** [comment]
@jcesarmobile I would like to go with Gradle 8 as soon as it is out of beta.

I started merging in the next major PRs. I will also be preparing and working on the tooling majors simultaneously. In the meantime, we could delay the release while working on tooling and hope Android Gradle Plugin 8's official release is done.

Also, isn't there a release candidate stage? I am wondering if it will take longer than we hope.

Additionally, we could just merge in and create another PR when it appears.

**Comment by erisu** [comment]
Sorry, I am talking about **Android Gradle Plugin 8.0** for Gradle 8.0 support

The current released plugin does not support Gradle 8.0. The Android Gradle Plugin 8.0 is still in beta and has not reached release candidate stage.

**Comment by jcesarmobile** [comment]
Where do you see that it’s still beta?

here it says latest is 8.1 and doesn’t say anything about being beta
https://developer.android.com/studio/releases/gradle-plugin



Electric Eel requires a plugin version between 3.2-7.4

So not sure if using 8 or 8.1 will cause issues

**Comment by erisu** [comment]
@jcesarmobile https://developer.android.com/reference/tools/gradle-api this is where I read that AGP 8 still beta and the page was last updated 3 days ago.

**Comment by erisu** [comment]
Currently trying to change how handle the package name.

https://github.com/erisu/cordova-android/commit/83b944971c01e35cc8829d2ab4a1e3b05ed389bb

One of the newer versions of AGP deprecated setting the package name in AndroidManifest file. There is a print out about this deprecation.

The commit above is my current changes but there are still a few other areas that looks at AndroidManifest for the package name, including the testing.

**Comment by erisu** [comment]
@jcesarmobile, Android Gradle Plugin 8.0 has entered the release candidate stage.

Also, If we were to upgrade to AGP 8.0 in this release, it have to force everyone up to JDK 17. AGP 8.0 requires JDK 17.

Also, Android Studio Flamingo will bundle JDK 17. Flamingo is not in beta stage. It is still in the canary stage.

I still dont have an exact ETA for the Android release, but must be released no later then July for Google's August requirements.

I think we sometimes explain that users can and maybe should use the JDK version that is bundled with Android Studio, but I am nto sure if Flamingo will be avaialble before AGP 8.0 is released.

Maybe more documentation in how to support JDK 17 + JDK 11...

**Comment by jcesarmobile** [comment]
flamingo is RC, at least the macOS version
https://developer.android.com/studio/preview

> Android Studio Flamingo | 2022.2.1 RC 1

pretty sure they match the gradle plugin versions with the Android studio version

**Comment by erisu** [comment]
Awesome. I guess all pages were updated. [This page still says beta](https://developer.android.com/studio/preview/features).

And the part where I read canary was a misunderstanding. It was when [JDK 17 was bundled with Android Studio.](https://developer.android.com/studio/preview/features#jdk-17)

**Comment by erisu** [comment]
I will go ahead and open up this PR for a review and move forward with merging it in.

Since this PR contians code changes for fixing things that were deprecated in the recent 7.x bump, I will recommend a second PR that focuses on AGP 8.0 and Gradle 8.0.

**Review by breautek — APPROVED** [review]

**Comment by breautek** [comment]
Tested on a hello world app.

**Pull request merged**
