### PR TITLE
feat!: android 12 splash screen

### PR DESCRIPTION
**Pull request by erisu**
### Motivation and Context

Closes: #1313

Support Android 12 Splash Screen API and backwards compatibility

### Description

**Old Splash Screen**

* Drop old copy resources for previous previous splash screen plugin.
* Remove old resource files

**New Splash Screen**

* Created new template resources
* Added compat library to support older devices
* Added new `config.xml` `preference`
  * `AndroidPostSplashScreenTheme`
    * Considered as advance feature and use at own risk. Unsupported feature.
  * `AndroidWindowSplashScreenAnimationDuration`
    * Manages the duration of the animation, not the delay of the splash screen.
  * `AndroidWindowSplashScreenAnimatedIcon`
    * This contains the icon that is display on the splash screen.
    * Icon image can be either `xml` Android Drawable, or `png`.
    * Follow the design specs from Android: https://developer.android.com/guide/topics/ui/splash-screen#splash_screen_dimensions
  * `AndroidWindowSplashScreenBackground`
    * Background color of the splash screen. Default is white (`#FFFFFF`)
  * `AndroidWindowSplashScreenBrandingImage`
    * Adds an image to the bottom of the splash screen.
  * `AndroidWindowSplashScreenIconBackgroundColor`
* Continue support for `config.xml` `preference` with follow behavioural changes.
  * `AutoHideSplashScreen`
    * **Default=onPageFinished, onPageFinished does not mean JavaScript executed or finished loading. Only covers HTML**
  * `SplashScreenDelay`
    * `AutoHideSplashScreen` must be `true` to use.
    * **Default=-1 which represents `onPageFinished`.**
    * Can override with custom millisecond value. E.g. 3000 = 3 second delay.
  * `FadeSplashScreen`
    * Default = true
    * **Only controls the fade out.**
  * `FadeSplashScreenDuration`
    * Default=500ms (0.5 seconds)

### Testing

- `npm t`
- `cordova build android`
- `cordova run android`

| API 31 | API 23 |
| -- | -- |
| Screenshot_20220614_175352 | Screenshot_1655196639 |

Note: 
* Some simulators do not display the splash screen when launch from Android Studio. This appears to be a bug from AS. Launching the app from within the simulator will show the splash screen.
* The default splash screen is an XML Android Drawable. It has a resolution of 512x512. It is padded and the inner icon size is 384x384. It is also scalled by 50% and pivotX/Y of 256.

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Comment by erisu** [comment]
> I have some trouble with the branding image and think the documentation PR will be very important for this.

It seems that branding is actually not supported below API 31 and there is an issue ticket open about it. https://issuetracker.google.com/issues/194301890

**Comment by NiklasMerz** [comment]
> It seems that branding is actually not supported below API 31 and there is an issue ticket open about it. https://issuetracker.google.com/issues/194301890
> 
> 
> 
> Maybe I can remove the branding code since it is not working and dont know if it will be supported.

Or we just leave it in for future versions and put a hint in the docs?

**Review by breautek — APPROVED** [review]

**Review by jcesarmobile — CHANGES_REQUESTED** [review]
Looks good, but if I open the themes.xml in Android Studio it shows "errors" because it doesn't understand the theme properties.
The templates's app/build.gradle should include `implementation "androidx.core:core-splashscreen:${cordovaConfig.ANDROIDX_CORE_SPLASHSCREEN_VERSION}"` so it understands the properties.

Also, current default delay is 3000 and it's being changed to -1, we have to remember to document the "breaking" change

**Comment by erisu** [comment]
> Looks good, but if I open the themes.xml in Android Studio it shows "errors" because it doesn't understand the theme properties. The templates's app/build.gradle should include `implementation "androidx.core:core-splashscreen:${cordovaConfig.ANDROIDX_CORE_SPLASHSCREEN_VERSION}"` so it understands the properties.

I added the dependency back the app as well.

> Also, current default delay is 3000 and it's being changed to -1, we have to remember to document the "breaking" change

I am writting the splash screen docs as well. Since the plugin does not support iOS or Android, the repo should not keep the docs anyways cause it will lead to confusion on what support the plugin has. Those docs are being removed from the plugin repo.

**Review by jcesarmobile — APPROVED** [review]

**Comment by NelsonChad** [comment]
Hi ,when i run cordova platform add android@11.0.0 I'm getting this error in prepare.js file

```
TypeError: Cannot read properties of null (reading 'find')
at E:\DEV\IONIC\donateApp_cord\node_modules\cordova-android\lib\prepare.js:387:49
at Array.forEach (<anonymous>)
at updateProjectSplashScreen (E:\DEV\IONIC\donateApp_cord\node_modules\cordova-android\lib\prepare.js:384:7)
at updateProjectAccordingTo (E:\DEV\IONIC\donateApp_cord\node_modules\cordova-android\lib\prepare.js:269:5)
at E:\DEV\IONIC\donateApp_cord\node_modules\cordova-android\lib\prepare.js:67:21
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Promise.all (index 0)
[ERROR] An error occurred while running subprocess cordova
```.

I've configurated de config.xml as recommended, can you help me please?

**Comment by ATaysikuu** [comment]
Hey, same issue here trying to upgrade a cordova 10 based project to cordova 11.

```
Cannot read property 'find' of null
TypeError: Cannot read property 'find' of null
    at C:\Jenkins\workspace\REDACTEDPROJECTNAME\node_modules\cordova-android\lib\prepare.js:387:49
    at Array.forEach (<anonymous>)
    at updateProjectSplashScreen (C:\Jenkins\workspace\REDACTEDPROJECTNAME\node_modules\cordova-android\lib\prepare.js:384:7)
    at updateProjectAccordingTo (C:\Jenkins\workspace\REDACTEDPROJECTNAME\node_modules\cordova-android\lib\prepare.js:269:5)
    at C:\Jenkins\workspace\REDACTEDPROJECTNAME\node_modules\cordova-android\lib\prepare.js:67:21
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
[ERROR] An error occurred while running subprocess cordova.
        
        cordova platform add android@11 --verbose --save exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
```

**Pull request merged**
