### PR TITLE
[CB-10916] Support display name for Android

### PR DESCRIPTION
**Pull request by dpogue**
This is the Android Platform API support side of https://github.com/apache/cordova-lib/pull/453.

### CODE REVIEW

**Comment by infil00p** [comment]
Looks fine, but we should wait for it all to go in together if possible.  @dpogue You have commit rights, so can you make sure that this gets pulled in when the parent issue gets resolved?

**Comment by dpogue** [comment]
Will do :+1:

**Comment by shazron** [comment]
iOS, cordova-lib has this pulled in, and also docs has a PR. Just waiting on this one to be pulled in.

**Comment by infil00p** [comment]
This appears to have fell by the wayside.  Why hasn't this been pulled into cordova-android?

**Comment by dpogue** [comment]
Sorry, been on vacation the past few weeks, but it looks like we've already bundled in the required version of cordova-common, so this is good to go!

**Pull request merged**
