### PR TITLE
Remove uses-sdk from AndroidManifest.xml

### PR DESCRIPTION
**Pull request by brodybits**
since uses-sdk values are now superseded by Gradle files

see #629 

P.S. Changes should be merged as a squash merge.

P.P.S. Here is the context:

- the SDK values in AndroidManifest.xml are now ignored by the Gradle scripts, as discussed in #508;
- keeping the SDK values in AndroidManifest.xml leads to some error messages in Android Studio, as discussed in #629;
- a fix to use the correct SDK values was already proposed in PR #655. I would like to get this proposal reviewed and merged before finishing the rework in PR #655.

### CODE REVIEW

**Comment by oliversalzburg** [comment]
LGTM

**Comment by janpio** [comment]
This PR removes the handling of the values/attributes that should not be used any more. Do we also have the part where the replacement is set in `build.gradle` somewhere? I am missing this context here.

**Comment by brodybits** [comment]
I just added the context to the description, hope it is clear enough now.

**Comment by janpio** [comment]
So merging this will break the code without #655 being merged as well?

**Comment by brodybits** [comment]
Merging this should not break anything that is not already broken. There exists issue #508 since Gradle does not use the information from AndroidManifest.xml. So my idea is to fix it in multiple steps:

- first step: remove the thing that is no longer wanted, as proposed here
- second step: fix the problem, as proposed in #508

**Comment by brodybits** [comment]
Thanks @janpio for the quick review!

**Comment by brodybits** [comment]
Something went wrong. I discovered that a result of this change is that the APK is generated with a nonsense target SDK value. This is because while the existing Gradle scripts *do* supersede the minSdkValue from AndroidManifest.xml, it *do not* supersede the targetSdkValue from AndroidManifest.xml. I will raise a new issue to describe the problem and discuss alternative solutions really soon.

My apologies.

**Pull request merged**
