### PR TITLE
[Gradle Syncs] Gradle 6.8.3 & Android Gradle Plugin 4.1.3 & Kotlin 1.4.31

### PR DESCRIPTION
**Pull request by mosabab**
### Platforms affected
Android

### Motivation and Context

[To keep Android projects sync with latest Gradle versions and anything related to Gradle]

As Android Gradle plugin release notes https://developer.android.com/studio/releases/gradle-plugin#updating-gradle
Related to Gradle version and Android Gradle Plugin.

Also Android Studio Version 4.1.3 update the Kotlin to 1.4.31
https://developer.android.com/studio/releases#4.1-kotlin

Here what the the version updates:

- Gradle version to 6.8.3
- Android Gradle Plugin version to 4.1.3
- Kotlin to 1.4.31

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [x] I added automated test coverage as appropriate for this change
- [x] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Comment by mosabab** [comment]
@breautek please look at this PR, this PR to sync Gradle with latest version of Android Studio 4.1.2

**Review by erisu — CHANGES_REQUESTED** [review]
I want this single PR to be split up into two or three separate PRs.

1. `feat: upgrade gradle@6.8.3`
2. `feat: upgrade gradle-plugin@4.1.3`
3. `feat: upgrade kotlin@1.4.31`

We generally squash merge PRs. Also if we need to revert a change because of issues, we will revert the entire PR. This means everything will be dropped.

IMO, seeing that these changes only updates to the latest minor release, it should be safe to be in the next minor release.

Also, I do not see why this PR contains code changes in `CordovaWebViewImpl.java` for this type of PR. It should be removed. I suspect because your not creating branches for your work your mixing to many things.

**Comment by mosabab** [comment]
> I want this single PR to be split up into two or three separate PRs.
> 
> 1. `feat: upgrade gradle@6.8.3`
> 2. `feat: upgrade gradle-plugin@4.1.3`
> 3. `feat: upgrade kotlin@1.4.31`
> 
> We generally squash merge PRs. Also if we need to revert a change because of issues, we will revert the entire PR. This means everything will be dropped.
> 
> IMO, seeing that these changes only updates to the latest minor release, it should be safe to be in the next minor release.
> 
> Also, I do not see why this PR contains code changes in `CordovaWebViewImpl.java` for this type of PR. It should be removed. I suspect because your not creating branches for your work your mixing to many things.

Thanks for explain!
Done

**Comment by erisu** [comment]
Thank you! 🙏 

I have finished reviewing the new PRs and will plan to merge them in by Tuesday next week.

**Pull request closed without merging**
