### PR TITLE
CB-12453: Remove unnecessary double quotes from .bat files which are the causes of crash if project path contains spaces

### PR DESCRIPTION
**Pull request by matrosov-nikita**
### Platforms affected
self

### What does this PR do?
This PR fixes bug with crash if project path contains spaces

### What testing has been done on this change?
Current auto-tests don't work if project path contains spaces, this PR fixes it

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [x] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by infil00p** [comment]
@filmaj Can you look at this?

**Comment by filmaj** [comment]
Yep, will take a look.

I would feel better about merging in #391 first, as that would run the end to end tests on appveyor (windows-based CI), which would validate some of this stuff in an automated way rather than relying on manual testing.

I'm surprised removing quotes from a .bat file is the solution, but then again I don't know a lot about .bat syntax :P

**Comment by filmaj** [comment]
@matrosov-nikita can you rebase with latest master in here?

**Comment by filmaj** [comment]
I've merged in the e2e testing changes on Appveyor (Windows) into master, so a rebase should trigger running these changes in a Windows environment via our CI.

**Comment by matrosov-nikita** [comment]
This bug affects user only if project path includes spaces.

Repro steps:
1) Create project in folder with space in name (i.e `C:\my projects\sample`)
2) Run `cordova run android --list`


On [this line](https://github.com/apache/cordova-android/blob/master/bin/templates/cordova/lib/list-devices.bat#L21) `%script_path%` already enclosed with double quotes. When we make additional enclosing, double quotes in the start and end of the script path are collapsed (""C:\my projects\sample\platforms\android\cordova\lib\list-devices"") and it leads to error like this: `Error: Cannot find module 'C:\my'`.

**Comment by matrosov-nikita** [comment]
Regarding changes in `spec/e2e/helpers/projectActions.js`, script path within this [command](https://github.com/apache/cordova-android/blob/master/spec/e2e/helpers/projectActions.js#L48) is not enclosed with double quotes and if [platformpath](https://github.com/apache/cordova-android/blob/master/spec/e2e/helpers/projectActions.js#L42) is not defined, it affects `create.spec.js` and `update.spec.js`.

**Comment by matrosov-nikita** [comment]
@filmaj, done.

**Pull request closed without merging**
