### PR TITLE
7.1.3 patch updates

### PR DESCRIPTION
**Pull request by brodybits**
## Changes ported

* Incorrect default sdk version issue fix (PR #495) & update comments in build.gradle (PR #496)
* Remove obsolete check for JellyBean to work properly on Android Pie (GH-534) (PR #544)
* GH-539 & GH-540 fix destination path fallback & fix for source-file with app target-dir, with unit test updates (PR #542)
* GH-547 fixes, with unit test updates from PR #550
* add missing cast for cdvMinSdkVersion (GH-551)
* Multiple build-extras.gradle locations (GH-552)

### npm test

- [x] `npm run unit-tests` succeeds
- [x] `npm test` succeeds in Travis CI and AppVeyor CI

### cordova-sqlite-storage 2.1.5

In a clone of <https://github.com/brodybits/cordova-sqlite-test-app>

* `cordova platform add https://github.com/brodybits/cordova-android#7.1.3-patch-updates`
* `cordova plugin add cordova-sqlite-storage@2.1.5`
* Able to build and run on a test device
* Click on self test button results in an alert that the self test is OK (self test of SQLite CRUD operations in sqlite plugin)
* `cordova plugin remove cordova-sqlite-storage` is successful

### Other plugins tested

Add plugin, build, and remove plugin tested for:

- [x] `cordova-plugin-deezer`
- [x] `https://github.com/adjust/cordova_sdk#master`
- [x] `https://github.com/adjust/cordova_sdk#cordova-8`
- [x] `https://github.com/dylearning/cordova-plugin-hikvisionVedio#master`
- [x] `https://github.com/j3k0/cordova-plugin-purchase#v7.1.0` (old version, without adaptations that were needed for cordova-android@7.0.0)

### CODE REVIEW

**Comment by jcesarmobile** [comment]
I don't see https://github.com/apache/cordova-android/pull/551 fix in the resulting changes

**Comment by brodybits** [comment]
I just finished testing the patch updates with some plugins listed in the OP description, quick review would be appreciated.

**Comment by brodybits** [comment]
I just pushed a change to remove the GH-547 fix for aidl files. This means that plugins such as cordova-plugin-purchase would need to keep multiple aidl `source-file` entries to support both cordova-android@6 and cordova-android@latest.

This is needed to avoid breaking plugins such as cordova-plugin-purchase in a patch release. I suspect we should push this change to master to avoid breaking plugins such as cordova-plugin-purchase in the foreseeable future.

**Comment by brodybits** [comment]
Back to WIP for now

**Comment by brodybits** [comment]
Waiting for final approval of <https://github.com/apache/cordova-android/pull/561>, which is expected to be merged as a merge commit. I will include the merge commit in this proposal once it is available.

**Comment by janpio** [comment]
Maybe silly question, but what would be a way to compare `master` and this branch to see if the cherry-picked commits make sense and nothing is missing etc?

**Comment by jcesarmobile** [comment]
No, because master have a lot more fixes that won't go into 7.1.3, so you can't directly compare

Also no to 7.2.0, this is supposedly a patch, and doing a minor bump will prevent the cli from getting this version that patches some bugs we caused in previous release

Will review later tonight

**Comment by brodybits** [comment]
I just updated the changes as follows:
* moved a couple gradle updates to the end
* added number of original PR on master where it was not present

I also updated the description to list the changes in the same order as they appear in this PR.

I hope this makes it easier to check what changes are in this PR. Thanks @jcesarmobile for your efforts to check the changes in both branches.

**Comment by brodybits** [comment]
Thanks @jcesarmobile!

**Pull request merged**
