### PR TITLE
CB-14165 : (android) Fix for device still connecting issues

### PR DESCRIPTION
**Pull request by gegenokitaro**
### Platforms affected
Android (Emulator)

### What does this PR do?
Add fix for 'device still connecting' problem when using android emulator

### What testing has been done on this change?
launching cordova emulate android

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [x] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by raphinesse** [comment]
Thanks you very much for this fix! :bowing_man:

**Comment by MatanYed** [comment]
+1 guys just release the fix

**Comment by mrfatstrat** [comment]
This fix doesn't seem to be included in the latest release 7.1.1 which I would expect since the fix was done Jun 25th and the release Jul 12th, any particular reason for this?  I really need this one.

**Comment by janpio** [comment]
The release process of 7.1.1 was started Jun 19, 2018, which is a few days before this was merged.
The next release 7.1.2 whose preparation started Aug 2, 2018 will include this change.
(Yep, Cordova's release processes are a bit more complicated)

If you really need it, you can either install from `master` or the `7.1.x` branch (where this was merged in preparation for 7.1.2)

**Pull request merged**
