### PR TITLE
Update CordovaResourceApi.java

### PR DESCRIPTION
**Pull request by bikcrum**
Add FileUtils class to support URI to getting real file path for different APIs.

### Checklist
- [ ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by janpio** [comment]
Hey @bikcrum, thanks for this PR.

What is the motivation for and use of this change?
Is there a JIRA issue that belongs to this code change?

**Comment by bikcrum** [comment]
@janpio I got some permission error while uploading media from Android API > 23. So I made changes to support for various Android APIs and it worked well.

**Comment by brodybits** [comment]
Can we move some of this functionality into a plugin?

**Comment by brodybits** [comment]
I think this needs investigation, adding the **discussion** label for now.

**Comment by lovelyelfpop** [comment]
Get real path of a content uri is not possible on Android Q+, `CordovaResourceApi.java` need fefactoring

**Comment by erisu** [comment]
I am closing out this ticket. I believe that,

* the request of this PR outdated
* there is a lot of overlap with the cordova-plugin-camera. If there are any changes needed, add them to the camera plugin.
  * If the changes are not camera-specific, maybe start a discussion to migrate the class to the file plugin and make the file plugin a dependency of the camera?
* there might be other changes needed since the PR creation to resolve major changes in the SDK 30 scope.

Additionally, there hasn't been any movement or discussion since 2018.

**Pull request closed without merging**
