### PR TITLE
[Android] Added support for BoM imports

### PR DESCRIPTION
**Pull request by ebhsgit**
### Platforms affected

Android

### Motivation and Context

Bill of Material (BoM) pattern simplifies the management of dependency versions (when there are multiple packages with shared dependencies).
https://docs.gradle.org/current/userguide/platforms.html#sub:bom_import

A cordova plugin may want to use BoM to manage the versions of it's dependencies.

Currently there is no way to implement this:

- Package import can not be defined without a version defined
- No ability to import BoM platform

Example using Firebase BoM
https://firebase.google.com/docs/android/learn-more#bom

### Description

- `propertiesObj.systemLibs` regex - exclude any imports that contains `(` in it's package name
- Added `propertiesObj.bomPlatforms` - any value package which matches `platform("...")`
- Allow package to be imported without version. This will generate a warning in the console

### Testing

I was able to compile my project (with custom plugin) which uses Firebase BoM

### Checklist

- [ x ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ x ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Comment by ebhsgit** [comment]
@breautek 
Hi mate, Any way to get someone to review the PR?

**Review by breautek — APPROVED** [review]
lgtm

But please be patient on an actual merge -- Not sure if there will be another minor release or not for 10.x.

**Review by PieterVanPoyer — APPROVED** [review]
Hey

Is it possible to add some info about how to use this in a plugin?
Maybe some sample configuration/code from your plugin could clarify this a little bit?

Kind regards
Pieter

**Comment by ebhsgit** [comment]
@PieterVanPoyer No problems

Below is the key snippet that this PR would enable

```
    <platform name="android">
          
          // Other stuff

        <preference name="FIREBASE_BOM" default="28.3.0" />

        <framework src="platform('com.google.firebase:firebase-bom:$FIREBASE_BOM')" />
        <framework src="com.google.firebase:firebase-auth" />
        <framework src="com.google.firebase:firebase-firestore"/>
        <framework src="com.google.firebase:firebase-messaging"/>

         // Other stuff

    </platform>
```

I've attached an example plugin.xml which enables firebase dependencies using BoM

[plugin.zip](https://github.com/apache/cordova-android/files/7132376/plugin.zip)

**Comment by breautek** [comment]
We have 2 green checks and master is in 11.x dev state so merging!

Thank you @ebhsgit for your contribution and effort into preparing this PR.

**Pull request merged**
