### PR TITLE
Upgrade build jdk from 6 to 7

### PR DESCRIPTION
**Pull request by Tneciv**
Upgrade build java version from java 6 to 7

### Platforms affected
Android

### What does this PR do?
Upgrade build java version to apply higher jdk features

### What testing has been done on this change?
Test to build apk successful

### Checklist
- [ ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by filmaj** [comment]
Is a Java upgrade required?

If so, then we should also update the [README's requirements section](https://github.com/apache/cordova-android/blob/master/README.md#requires).

**Comment by infil00p** [comment]
Yeah, I'm not sure this is such a great plan.

**Comment by filmaj** [comment]
@infil00p so what's the plan here? Are these changes to readme/JDK requirements unfounded? Close this?

**Comment by infil00p** [comment]
I think this should be discussed on the list.  There's upsides and downsides to this, and it could attract more developers to adopt JDK 7 and newer Java features.

**Comment by infil00p** [comment]
Well, that's embarrassing.  Let's just skip 7 for 8?

**Comment by infil00p** [comment]
See #407, we kinda missed the boat on Java 7. :/

**Pull request closed without merging**
