### PR TITLE
feat!: Upgrade to Gradle and AGP 8

### PR DESCRIPTION
**Pull request by jcesarmobile**

### CODE REVIEW

**Comment by erisu** [comment]
@jcesarmobile try updating this line to use JDK 17. Include title change.

https://github.com/apache/cordova-android/blob/master/.github/workflows/ci.yml#L41-L45

**Comment by jcesarmobile** [comment]
updated gradle to 8.0.2 as gradle website recommends using that over 8.0

**Comment by breautek** [comment]
The [README](https://github.com/apache/cordova-android/blob/master/README.md?plain=1#L35) should be updated to reflect the new JDK requirement.

Part of me would rather wait for AGP 8 support until we intend to support API 34, which is still in beta phase and won't be released until August at the earliest. I see no concrete date in their roadmap for the final release. The rationale for waiting is to defer the JDK 17 upgrade when it's not needed for a future cordova-android@13 release for API 34. I think Cordova should release a version supporting API 33 no later than at the end of July to give the month to users to refactor their own apps.

On the other hand, we do have an issue with M1 macs where it can be rather [difficult](https://github.com/apache/cordova-android/issues/1409#issuecomment-1510008696) to setup due to the current JDK 11 requirement which the only prebuilt JDK available and is provided through Android Studio Electric Eel. Now that Flamingo is released, I presume it ships with JDK 17 which I've seen reports that it doesn't work properly with the Android Tooling (however I haven't confirmed this myself). So having build tools that supports JDK 17 will now give M1 users more options as there are other prebuilt JDK environments available and would be more aligned to our existing documentation.

**Comment by breautek** [comment]
Also related: https://docs.gradle.org/7.6/userguide/upgrading_version_7.html#configuring_custom_build_layout

We use `-b` flag currently to specify where our build config is. Not sure if this is even necessary however.

**Comment by breautek** [comment]
> Do you recommand sir @breautek to downgrade or to wait for the new release ? (my company is in harry to deploy their first app on the store , so maybe we gonna traget sdk 32 only)

To add to jcesar's comments, cordova-android@12 is not going to support AGP 8 or JDK 17. JDK 17 will probably still work for the most part, but it will probably be best to use the recommended JDK for AGP 7 which is JDK 11. JDK 17 may not work completely as expected when using it with AGP 7.

The namespace attribute came in AGP 7.4 or 7.5 (I forget which version exactly) but cordova-android@12 will configure the app & cordova framework to use the `namespace` attribute.

cordova-android@12 is currently being voted on for release (See the [Vote Thread](https://lists.apache.org/thread/f0rgv8dc66lxsq0hnfkdny928ko4yc4d)). So if you gave nightly a test, consider giving us feedback in the [DISCUSS](https://lists.apache.org/thread/f0rgv8dc66lxsq0hnfkdny928ko4yc4d) thread and maybe a +1 or a -1 in the [VOTE](https://lists.apache.org/thread/f0rgv8dc66lxsq0hnfkdny928ko4yc4d) thread.

If you need more information on how Apache voting works, see [Apache Voting Process](https://www.apache.org/foundation/voting.html).

On AGP 8 / Gradle 8 support, as of writing I think that is planned for another major release, probably cordova-android@13.

**Pull request closed without merging**
