### PR TITLE
GH-621 android: Added multiple selection for filepicker

### PR DESCRIPTION
**Pull request by MatusFiala**
### Platforms affected
Android

### What does this PR do?
Allows filepicker to select multiple files.

### What testing has been done on this change?
Checked locally

### Notes on testing on devices 
Tested on following devices:
- Moto G5 (Android 7.0)
- Nexus 5X (Android 8.1)
- Samsung Galaxy Tab S4 (Android 8.1)
- Sony Xperia XZ2 Compact (Android 9.0)
- Nexus 7 (Android 6.0.1)
- Sony Xperia Z2 (Android 5.1.1)

The multiple file selection works basically, but behaves different on different devices/software.
#### Device difference:
On the Moto G5 and Samsung Tab it behaves like expected. Simply use long press (on file explorer, media-gallery, etc ) to start multiple selection.
The Nexus starts the filepicker with multiple selection enabled without using long-press.
#### Software-difference (on Samsung Tab):
- normal file-picker: Works like expected
- Google pictures-app: Starts with multiple selection enabled
- Samsung Gallery: Multiple selection does not work when using as filepicker
#### Software-difference (on Sony Xperia XZ2 Compact + Z2):
- normal file-picker: Works like expected
- Google pictures-app: Starts with multiple selection enabled
- Sony Picture Gallery: Multiple selection does not work when using as filepicker

The reason for this different behaviour is due to the different retun value of the filepicker-intent.
Normally when selecting one file, the intent writes the URL to the 'normal' data field, and when multiple files are selected to the clipData array. This works fine with the Samsung tab and Moto G5. But the intent of the Nexus always writes the first selected file to the data field, even though multiple files are selected. That's why I first check the clipData before the normal data.

Used this stackoverflow anser as inspiration: https://stackoverflow.com/questions/39390781/crosswalk-cordova-android-multiple-file-select

### Update 25.03
Tested all nadorid versions from 5 - 9. Always the same behavior:
- normal filepicker works perfect
- brand specific file picker can only choose 1 object
- Google Fotos has multiple selection always activated

### Checklist
- [ ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by brodybits** [comment]
I would favor a solution where `onShowFileChooser` would be handled by one or more plugins.

**Comment by dpogue** [comment]
You should not need plugins for `<input type="file" multiple>` to work. That's basic web functionality

**Comment by brodybits** [comment]
Right.

So the Android WebChromeClient interface provides us a way to customize how we should handle this functionality, and we blindly start a built-in file chooser. I wonder if we should consider a way to do this in a more flexible manner?

**Comment by artuska** [comment]
When this PR will be merged?

**Comment by janpio** [comment]
When it is fully tested and reviewed. Can you confirm this feature works (on all Android versions= and doesn't break anything else?

**Comment by StarStep** [comment]
Work great on android 8.1.0

**Comment by MatusFiala** [comment]
What do you need for a merge? Do you need another tests for Androdi 5, 6 and 9 (7 and 8.1 already tested)? How can I help?

**Comment by MatusFiala** [comment]
Tested on Sony Xperia XZ2 Compact (Android 9). 
Same behavior as the Samsung Tab.
Normal filepicker works, brand specific filepicker does not support multiple selection. 

I am gonna test Android 5 and 6 next week. Just need some devices.

**Comment by MatusFiala** [comment]
Finally found some devices with Android 5 and 6.
Tested devices:
- Nexus 7 (Android 6.0.1)
- Sony Xperia Z2 (Android 5.1.1)

Same behaviour as every other device.
- normal filepicker works perfect
- brand specific file picker can only choose 1 object
- Google Fotos has multiple selection always activated

**Pull request merged**
