### PR TITLE
CB-14240 - Cherry pick some android fixes from master to 7.1.x

### PR DESCRIPTION
**Pull request by jcesarmobile**
### Platforms affected
android

### What does this PR do?
cherry pick some master fixes to 7.1.x branch

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by jcesarmobile** [comment]
I tried and git told me it was already there, checked the code and it seems that it's really there, and git log in 7.1.x branch also shows it there. Not sure why when you do a branch compare it shows it as not included.

**Comment by janpio** [comment]
Oh, fun. Cherry picking is a surprising pain sometimes.

**Comment by raphinesse** [comment]
#450 already was part of the last release

**Comment by brodybits** [comment]
I would personally favor marking 7.1.2-dev before cherry-picking the changes, like I did in GH-454, apache/cordova-ios#379, and other places. I think this should be fixed in cordova-coho doc.

**Comment by janpio** [comment]
Isn't it that way for `master` already? Probably nobody thought about releases from the version branches much.

**Comment by janpio** [comment]
Then it probably makes sense to be fixed in coho.

**Comment by brodybits** [comment]
I just raised <https://issues.apache.org/jira/browse/CB-14249>, don't know when I will get a chance to take care of this one. Further discussion should probably be there or on mailing list.

**Pull request merged**
