### PR TITLE
CB-11138 Reuse PluginManager from common to add/rm plugins

### PR DESCRIPTION
**Pull request by vladimir-kotikov**
A change to use `PluginManager` class to manage plugin installation/uninstallation instead of custom logic

JIRA: [CB-11138](https://issues.apache.org/jira/browse/CB-11138)

### CODE REVIEW

**Comment by nikhilkh** [comment]
@jasongin Can you please help review.

**Comment by jasongin** [comment]
Can I ignore all the changes under node_modules? I don't understand why that is checked in to source control...

**Comment by vladimir-kotikov** [comment]
Sure, you can skip them safely. This is because we ship them as 'bundled' dependencies, since we don't run `npm install` after downloading the platform.

**Comment by jasongin** [comment]
:+1:

**Pull request closed without merging**
